apiVersion: dapr.io/v1alpha1
kind: Component
metadata:
  name: qiqosoft-pubsub
spec:
  type: pubsub.rabbitmq
  version: v1
  metadata:
  - name: host
    value: "amqp://guest:guest@qiqosoft-rmq.default.svc.cluster.local:5672"
  - name: durable
    value: true
  - name: deletedWhenUnused
    value: true