### for docker

GET http://localhost:8080/api/v1/Accounts

### for k8s; port may change

GET http://localhost:30621/api/v1/Accounts

### for dapr

### GET http://localhost:3500/v1.0/invoke/accounts-api/method/accounts